### PR TITLE
Contact

### PR DESCRIPTION
**Pull request by RoboTeddy**

### CODE REVIEW

**Comment by lrq3000** [comment]
Hello Ted,

Thank you for contacting me and your offer :-)

You are right that I forgot to add contact details, usually I add it in the sourcecode (because if it's in the README I get spammed to death by bots...) but here there is no sourcecode. I have opened a Discussions pane for future contact needs, and I'm going to send you an e-mail so you can contact me this way too. I'm going to reply here for now, but feel free to contact me by e-mail if you prefer to continue this discussion in private.

I know of some studies that used wavelength transforms successfully to detect circadian rhythm cycles so your approach is sound indeed! I am sure your tool can be helpful to others, and I would be interested to use it myself and potentially expand it later as part of the [circalizer](https://github.com/Circadiaware/circalizer) project. If you are open to publish your software under an open-source license of your choice, then I can create a github repository under the Circadiaware organization, that you'll have full access to. And don't worry about code quality or missing features or bugs, I or others can take care of that, your contribution as it is today is already awesome, so don't bother :-)

As a quick summary of what is the Circadiaware initiative, its goal is to centralize, maintain and promote open-source solutions for the management and treatment of circadian rhythm disorders. It's basically intended to be just a collective of developers.

If I may ask out of curiosity, do you have a circadian rhythm disorder or are you studying the circadian rhythm for other reasons? Did you see the other projects in the Circadiaware initiative, maybe they can also be of interest to you?

**Comment by lrq3000** [comment]
Dear @RoboTeddy , do you still wish to release your code under open-source? Don't worry about the details, we can help you for any practical details of uploading and maintaining the package in the future :-)

**Comment by RoboTeddy** [comment]
Yes, sorry, just been distracted!

**Comment by lrq3000** [comment]
@RoboTeddy Great! :D I have created a new repository and invited you, please check your emails or github notifications to see and accept the invitation to receive the write permissions on this repository : https://github.com/Circadiaware/coretemp-cwt

I did not set a license so that you can choose the one you prefer. I'm very interested to see how well your algo can perform on partial data, and how you can download data from the core sensor, or is it from the cloud?

Please let me know if you need help for anything! And please don't worry about code quality, sharing your work is already marvelous!

**Comment by RoboTeddy** [comment]
Great! Added the files (dedicated to public domain)

Sadly FYI the only good cwt library I could find was part of matlab, which is not open source, and furthermore requires a matlab wavelet extension which also costs extra :( There's some kind of python cwt library out there, but iirc it didn't support some features that I wanted.

Not sure if the code is still functional against corebodytemp's website, since I haven't run my code in a while. Will be analyzing a friend's CORE temp data soon, so will probably update code at that point if anything is out of date.

Note also that I also set it up to grab Fitbit data (was planning on overlaying the data), which is extraneous for our purposes here.

**Comment by RoboTeddy** [comment]
Oh and since it's annoying that it depends on matlab — if you'd like an analysis of your own data, feel free to send me a .csv file and I'll try running it through the matlab script and sending you back a screenshot of the fit as well as the numeric temperature nadir times of each day.

**Comment by lrq3000** [comment]
@RoboTeddy Thank you so much for sharing your work, and under public domain, that's awesome! I will still make sure you get credited by courtesy in all the Circadiaware projects where your code/idea may be used :-)

No worries about MATLAB, I use it all the time for work, in neuroscience it's the most used programming language, before Python :-) But just to make sure I got the compatibility right, could you please tell me what MATLAB version you used? Functions behaviors can change between releases but I can trace changes with the official logs on their website :-)

Thank you for pointing out the limitations of Python for wavelet analysis, if I have some time I will try to see if it's possible to reproduce in Python, sometimes there are obscure python modules made by scientists that are hard to find but can do the work in Python, we'll see :-)

**Pull request closed without merging**
